# Whether the deployment artifacts should be present in your project
present: "true"

# The username and password of the dockerhub account with access to the images. This is needed to pull the IO AMR images for the simulation
docker_user: "insert username"
docker_password: "insert password"

# The images used for the simulation
rio_simulator_image: "rrdockerhub/io_amr_pa:sim_stable"
rio_gwm_ui_image: "rrdockerhub/io_amr_ui:sim_stable"
rio_db_image: "mdillon/postgis:latest"
rio_gwm_image: "rrdockerhub/io_amr_gwm:sim_stable"

prefix_name: "prefix"
site_name: tatsumi

# if routed_networks is set to true, please remember to deleted the routed network after deprovisioning
routed_network: false
ansible_async: true

# Simulation parameters
item_spawn_from: AUTO


# Source project package info
source_project_id: project-xbaeosxiygjtkhuanbwhjmhi
source_auth_token: E6zgG9mP3L8jjDRLVKAXhf9Xu1MYwwnECjikxgvC
