present: "false"
docker_password: "#3=L#L_UVSDT{enY"
rio_amr_pa_image: "rrdockerhub/io_amr_pa:jwciio"
rio_gwm_ui_image: "rrdockerhub/io_amr_ui:jwciio"
rio_db_image: "rrdockerhub/rr_amr_postgres:nightly"
rio_gazebo_image: "rrdockerhub/io_amr_pa:jwciio"
rio_gbc_image: "rrdockerhub/io_amr_pa:jwciio"
rio_gwm_image: "rrdockerhub/io_amr_gwm:jwciio"
rr_gwm_static_route: "io-gwm-jwciio"
rr_gbc_static_route: "io-gbc-jwciio"
amr_ui_static_route: "amr-ui-jwciio"
gazebo_ui_static_route: "gazebo-ui-jwciio"