present: "true"
docker_password: "#3=L#L_UVSDT{enY"
rio_amr_pa_image: "rrdockerhub/io_amr_pa:release_05_21-10_amr"
rio_gwm_ui_image: "rrdockerhub/rr_amr_ui:release_05_21"
rio_db_image: "rrdockerhub/rr_amr_postgres:nightly"
rio_gwm_image: "rrdockerhub/rr_amr_gwm:release_05_21"
static_route_postfix: "demo"
