present: "true"
docker_password: "some_password_here"
rio_amr_pa_image: "rrdockerhub/io_amr_pa:release_05_21-10_amr"
rio_gwm_ui_image: "rrdockerhub/rr_amr_ui:release_05_21"
rio_db_image: "rrdockerhub/rr_amr_postgres:nightly"
rio_gwm_image: "rrdockerhub/rr_amr_gwm:release_05_21"
static_route_postfix: "demo"
prefix_name: test
agent_list:
  - { id: '1', x: '6.2', y: '12' }
  - { id: '2', x: '11', y: '12' }
  - { id: '3', x: '13.6', y: '1.3' }
  - { id: '4', x: '21.9', y: '11.2' }
  - { id: '5', x: '1.4', y: '3.5' }
  - { id: '6', x: '14.4', y: '9.4' }
  - { id: '7', x: '15.4', y: '5.9' }
  - { id: '8', x: '16.5', y: '2.9' }
  - { id: '9', x: '5.8', y: '6.9' }
  - { id: '10', x: '8.4', y: '12' }
