# Whether the deployment artifacts should be present in your project
present: "true"
db_persist: "false"

# The username and password of the dockerhub account with access to the images. This is needed to pull the IO AMR images for the simulation
docker_user: "insert username"
docker_password: "insert password"

# The images used for the simulation
postgres_version: "v99.99.99"
postgres_cloud_version: "v99.99.99"
amr_version: "v22.3.1-0"
amr_ui_version: "v22.3.1-0"
amr_ui_cloud_version: "v99.99.99"
gwm_version: "v22.3.1-0"
gwm_cloud_version: "v99.99.99-0"
server_version: "v22.3.1-0"
server_cloud_version: "v22.3.1-0"
simulator_version: "v99.99.99-0"

prefix_name: "prefix"
site_name: kiba

# if routed_networks is set to true, please remember to deleted the routed network after deprovisioning
# Either "routed" or "native"
network_type: "routed"
ansible_async: true
ros_distro: noetic


volume_name: "" # will look for a disk with this name, if volume deploy is true, script will create a disk with this name and use it
volume_deploy: false
volume_capacity: 4GiB #This parameter is case insensitive.
    #choices:
    #- 4GiB
    #- 8GiB
    #- 16GiB
    #- 32GiB
    #- 64GiB
    #- 128GiB
    #- 256 GiB
    #- 512 GiB

# replace robot_device_1, robot_device_2, robot_device_3 with the name of the robot device you wish to use
# Add any Component Parameters into the {} as a comma seperated list of Key: Value pairs
# SITE is not needed if site_name is set, the component parameters for SITE will be automatically populated
# Empty values for the package component parameters will mean the deployment will use package defaults
# Package defaults for component parameters will be overwritten if they are specified here
robot_devices: {
 robot_device_1: {AUTOBOOTSTRAP: 'true'},
 robot_device_2: {},
 robot_device_3: {}
}

# Add any Component Parameters into the {} as a comma seperated list of Key: Value pairs after each Package key
# Each package argument is seperate from the others
# SITE is not needed if site_name is set, the component parameters for SITE will be automatically populated
# Empty values for the package component parameters will mean the deployment will use package defaults
# Package defaults for component parameters will be overwritten if they are specified here
package_arguments: {
  postgres: {},
  postgres_cloud: {},
  amr_ui: {},
  amr_ui_cloud: {},
  gwm: {},
  gwm_cloud: {},
  server: {
    AUTOBOOTSTRAP: 'true',
    SITE: 'kiba'
  },
  server_cloud: {
    AUTOBOOTSTRAP: 'true',
    SITE: 'kiba'
  },
  simulator: {
    AUTOBOOTSTRAP: 'false',
  }
}

nuc_device_name: jason
nuc_device_network_interface: wlp0s20f3
robot_device_network_interface: wlp1s0
