present: "true"
forklift_docker_read_password: ""
dockerhub_read_password: ""
rio_amr_pa_image: ""
rio_gwm_ui_image: ""
rio_db_image: "rrdockerhub/rr_amr_postgres:nightly"
rio_gwm_image: ""
prefix_name: forklift-multirobot-test
site_name: toyama

# AMR common parameters
amr_idle_timeout: 30 # s
amr_charge_time: 7200.0 # s

agent_list:
  - { id: '1001', x: '43.65', y: '24.74', yaw: '3.14', map_name: toyama_1F}
  - { id: '1002', x: '28.5', y: '38.7', yaw: '-1.57', map_name: toyama_1F }
  - { id: '1003', x: '45.1', y: '21.73', yaw: '0', map_name: toyama_1F }
  - { id: '1005', x: '30.23', y: '10.47', yaw: '1.57', map_name: toyama_1F }

