# Whether the deployment artifacts should be present in your project
present: "true"

# The username and password of the dockerhub account with access to the images. This is needed to pull the IO AMR images for the simulation
docker_user: "ioamr"
docker_password: "airb0urne"

# The images used for the simulation
postgres_version: "v1.0.0-3"
postgres_cloud_version: "v1.0.0-6"
amr_version: "v21.12.0-34"
amr_ui_version: "v2.5.0-4"
amr_ui_cloud_version: "v2.5.0-7"
gwm_version: "v0.3.0-6"
gwm_cloud_version: "v0.3.0-9"
server_version: "v21.12.0-11"
server_cloud_version: "v21.12.0-19"
simulator_version: "v21.12.0-12"

prefix_name: "docomo"
site_name: kiba

# if routed_networks is set to true, please remember to deleted the routed network after deprovisioning
# Either "routed" or "native"
network_type: "routed"
ansible_async: true
ros_distro: noetic

robot_device_name:
- stg1
- stg2
- stg3

nuc_device_name: jason
nuc_device_network_interface: wlp0s20f3
robot_device_network_interface: wlp1s0
