present: "true"
forklift_docker_read_password: ""
dockerhub_read_password: ""
rio_amr_pa_image: ""
rio_gwm_ui_image: ""
rio_db_image: "rrdockerhub/rr_amr_postgres:nightly"
rio_gwm_image: ""
prefix_name: forklift
site_name: toyama

# AMR common parameters
amr_idle_timeout: 300 # s
amr_charge_time: 7200.0 # s
enable_safety_zones: "false"

# Tracing for Debugging
tracing: "true"

agent_list:
  - { id: '1001', x: '43.65', y: '24.74', yaw: '3.14', map_name: toyama_1F, idle_x: '61.5' , idle_y: '32.1', idle_yaw: '-1.57'}
  - { id: '1002', x: '28.5', y: '38.7', yaw: '-1.57', map_name: toyama_1F, idle_x: '43.68' , idle_y: '24.65', idle_yaw: '3.14'}
  - { id: '1003', x: '45.1', y: '21.73', yaw: '0', map_name: toyama_1F, idle_x: '34.13' , idle_y: '30.637', idle_yaw: '1.57'}


