# Whether the deployment artifacts should be present in your project
present: "true"

# The username and password of the dockerhub account with access to the images. This is needed to pull the IO AMR images for the simulation
docker_user: "ioamrreadonly"
docker_password: "#3=L#L_UVSDT{enY"

# The images used for the simulation
rio_amr_pa_image: "rrdockerhub/io_amr_pa:sim_stable"
rio_gwm_ui_image: "rrdockerhub/io_amr_ui:sim_stable"
rio_db_image: "mdillon/postgis:latest"
rio_gwm_image: "rrdockerhub/io_amr_gwm:sim_stable"

prefix_name: "prefix"
site_name: tatsumi

# if routed_networks is set to true, please remember to deleted the routed network after deprovisioning
routed_network: false
tracing: "false"

# AMR common parameters
amr_idle_timeout: 30 # s
amr_charge_time: 7200.0 # s
amr_initual_battery_percentage: 1.0 # 1.0 == 100%
amr_charge_rate: 0.00007 # Linear increase rate of battery
amr_discharge_rate: 0.00003 # Linear decrease rate of battery
amr_critical_battery_timeout: 5 # s
amr_critical_battery_pct: -10.0 # %
amr_operational_battery_pct: 50.0 # %
amr_max_battery_pct: 90.0 # %
amr_charge_time_based: true
enable_speed_regions: true

# Simulation parameters
item_spawn_from: AUTO

agent_list:
  - { id: '1', x: '6.2', y: '12', charge_x: '6.2', charge_y: '14.02', idle_x: '6.2', idle_y: '12.0' }
  - { id: '2', x: '11', y: '12', charge_x: '8.38', charge_y: '14.02', idle_x: '11.0', idle_y: '12.0' }
  - { id: '3', x: '13.6', y: '1.3', charge_x: '10.88', charge_y: '14.02', idle_x: '13.6', idle_y: '1.3' }
#  - { id: '4', x: '21.9', y: '11.2', charge_x: '21.9', charge_y: '11.2', idle_x: '21.9', idle_y: '11.2' }
#  - { id: '5', x: '1.4', y: '3.5', charge_x: '1.4', charge_y: '3.5', idle_x: '1.4', idle_y: '3.5' }
#  - { id: '6', x: '14.4', y: '9.4', charge_x: '14.4', charge_y: '9.4', idle_x: '14.4', idle_y: '9.4' }
#  - { id: '7', x: '15.4', y: '5.9', charge_x: '15.4', charge_y: '5.9', idle_x: '15.4', idle_y: '5.9' }
#  - { id: '8', x: '16.5', y: '2.9', charge_x: '16.5', charge_y: '2.9', idle_x: '16.5', idle_y: '2.9' }
#  - { id: '9', x: '5.8', y: '6.9', charge_x: '5.8', charge_y: '6.9', idle_x: '5.8', idle_y: '6.9' }
#  - { id: '10', x: '8.4', y: '12', charge_x: '8.4', charge_y: '12', idle_x: '8.4', idle_y: '12' }