# Whether the deployment artifacts should be present in your project
present: "true"

# The username and password of the dockerhub account with access to the images. This is needed to pull the IO AMR images for the simulation
docker_user: "dsatherr"
docker_password: "Funny#Fish"

# The images used for the simulation
rio_db_image: "mdillon/postgis:latest"
tracing_agent_image: "jaegertracing/jaeger-agent"
rio_amr_pa_image: "rrdockerhub/io_amr_pa:iogen-build-fxxvhvnmgoudktpxproretbg-12"
rio_gwm_ui_image: "rrdockerhub/io_amr_ui:iogen-build-lebhajixfbcntjhyitmgjznw-4"
rio_gwm_image: "rrdockerhub/io_amr_gwm:21.12.0"

prefix_name: "testing"
site_name: kiba

# if routed_networks is set to true, please remember to deleted the routed network after deprovisioning
routed_network: true
native_network: false
ansible_async: true

robot_device_name: robot_device_name
nuc_device_name: nuc_device_name
nuc_device_network_interface: eno1
robot_device_network_interface: wlp1s0
