# Configurable Parameters
deployment_prefix: rr-abhinav
deprovision_routed_network: true
deprovision_db: false
deprovision_gwm: false

# Global Parameters
PROJECT_ID: project-uzcusgvxbomxzssmybsgcrxj
AUTH_TOKEN: C9WgSmSkPzvUt8FOHrn8kd7eDoNWKLfuZkQq668Y



#io-build, Docker from io-builder or other docker repo
SECRET: dockerhub
DOCKER_USERNAME: 'ioamrreadonly'
DOCKER_PASSWORD: '#3=L#L_UVSDT{enY'
DOCKER_EMAIL: 'rss2.admin@rapyuta-robotics.com'
BUILD:
    PA:
      DOCKER_IMAGE: rrdockerhub/io_amr_pa:iogen-build-hpbhoacrskuhegfptoygrloa-2
    AMR_UI:
      DOCKER_IMAGE: rrdockerhub/rr_amr_ui:iogen-build-ayttlohomqaxfzaphhboarou-1
    GWM:
      DOCKER_IMAGE: rrdockerhub/rr_amr_gwm:iogen-build-kidpzvcxkppzmpxveiocmrub-1
    DB:
      DOCKER_IMAGE: rrdockerhub/rr_amr_postgres:nightly

# DB
DB_PARAMS:
  POSTGRES_DB: gwm_core
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

# GWM 
GWM_PARAMS:
  AUTOBOOTSTRAP: true
  DEBUG: true
  DJANGO_LOG_LEVEL: WARNING

# GWM_UI
AMR_UI_PARAMS:
  SKIP_PREFLIGHT_CHECK: "true"
  GWM_API_VERSION: v1
  DEFAULT_GWM_INTERFACE_HOST: gbc
  DEFAULT_GWM_INTERFACE_PORT: 8080
  DEFAULT_GWM_INTERFACE_PROTOCOL: ws

# GBC
GBC_PARAMS:
  GWM_INTERFACE_SITE: tatsumi
  AUTOBOOTSTRAP: "true"
  GWM_INTERFACE_ORG_ID: 1
  GWM_INTERFACE_SITE_ID: 1
  GWM_INTERFACE_TOKEN: autobootstrap
  IO_AMR_GWM_INTERFACE_NODE_NAME: rr_gwm_interface
  ROSCONSOLE_FORMAT: "[$${severity}] [$${time}] [$${node} $${logger} $${function} $${line}]: $${message}"

# Simulator parameters
GAZEBO_PARAMS:
  VNC_PASSWORD: rapyuta
  VNC_RESOLUTION: 1920x1080
  DEBUG: true
  RACK: true
  WORLD: tatsumi
  ITEM_SPAWN_FROM: YAML

AMR_COMMON_PARAMS:
  ROBOT_MODEL: rr_pa_amr
  ROBOT_NAV_MODEL: rr_pa_amr
  NAV_STRATEGY: graph_guided
  MAP: tatsumi
  MAP_ID: 1
  WORLD2MAP_X: 0
  WORLD2MAP_Y: 0
  WORLD2MAP_Z: 0
  WORLD2MAP_YAW: 0
  IDLE_TIMEOUT: 1000000

AMR_PARAMS:
  - AGENT_ID: 1
    X_POS: 6.2
    Y_POS: 12
    Z_POS: 0.0
    YAW: 1.57
  - AGENT_ID: 2
    X_POS: 11
    Y_POS: 12
    Z_POS: 0.0
    YAW: 1.57
  - AGENT_ID: 3
    X_POS: 13.6
    Y_POS: 1.3
    Z_POS: 0.0
    YAW: 1.57
