# Configurable Parameters
deployment_prefix: example
deprovision_routed_network: true
deprovision_db: yes
deprovision_gwm: yes

# Global Parameters
PROJECT_ID: ENTER_PROJECT_ID
AUTH_TOKEN: ENTER_AUTH_TOKEN

# Docker Parameters
DOCKER_PASSWORD: "#3=L#L_UVSDT{enY"

# GWM Autobootstarp credentials
GWM_PARAMS:
  AUTO_ROOT_USER: autobootstrap
  AUTO_ROOT_PASS: autobootstrap
  AUTO_AUTH_TOKEN: autobootstrap