#!/bin/bash
NUM_AGENTS="$2"
HEAD="-H 'accept: application/json' -H 'X-RRAMR-Org: 1' -H 'X-RRAMR-Site: 1'  -H 'Authorization: token $3' -H 'Content-Type: application/json'"
URL="https://$1-gwm-kqdbp.ep-r.io/v1/agent"
for AGENT in $(seq 1 $NUM_AGENTS)
do
  BODY="{\"id\": $AGENT, \"name\": \"agent$AGENT\", \"robot_id\": $AGENT, \"robot_descriptor_id\": $AGENT, \"map\": 1}"
  curl -X 'POST' $URL -H 'X-RRAMR-Org: 1' -H 'X-RRAMR-Site: 1'  -H 'Authorization: token $3' -H 'Content-Type: application/json' -d "$BODY"
done