- name: Playbook Sanity checks and configuration
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: Test if the type of 'prefix_name' is string
      assert:
        that:
          - prefix_name is regex("^[a-zA-Z0-9\-]*$")
          - prefix_name != "prefix"
        fail_msg: prefix_name is not alphanumeric or is using the default 'prefix' name, please fix the prefix_name and try again
    - name: Test if docker username and password are still default vaules
      assert:
        that:
          - docker_user  != "insert username"
          - docker_password != "insert password"
        fail_msg: docker username or password is currently set as default values, please check both and try again
    - name: set_async_status
      set_fact:
        async_time: 0
      when: ansible_async|bool == false

- name: Secrets, Networks
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: Docker Secret
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.secrets:
        name: dockerhub
        present: "{{ present }}"
        type: docker
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        email: rss2.admin@rapyuta-robotics.com
      register: docker_secret_id
    - name: Native Network Deployment
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.networks:
        name: "{{ prefix_name }}_native_network"
        present: "{{ present }}"
        type: native_network
        ros_distro: melodic
        resource_type: small
      when: routed_network|bool == false
      register: native_network_id
    - name: Routed Network Deployment
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.networks:
        name: "{{ prefix_name }}_routed_network"
        present: "{{ present }}"
        type: routed_network
        ros_distro: melodic
        resource_type: small
      when: routed_network|bool == true
      register: routed_network_id

- name: POSTGRES, GWM, USER_INTERFACE, SIMULATOR Packages
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: postgres package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: postgres
        present: "{{ present }}"
        package_from: manifest_path
        manifest_path: /tmp/postgres.json
        executables_info:
        - name: pgsql
          type: docker
          docker_image: "{{ rio_db_image }}"
      register: postgres_package_id
    - name: gwm package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: gwm
        present: "{{ present }}"
        package_from: manifest_path
        manifest_path: /tmp/gwm.json
        executables_info:
        - name: core
          type: docker
          docker_image: "{{ rio_gwm_image }}"
          secret: dockerhub
      register: gwm_package_id
    - name: user_interface package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: user_interface
        present: "{{ present }}"
        package_from: manifest_path
        manifest_path: /tmp/user_interface.json
        executables_info:
        - name: core
          type: docker
          docker_image: "{{ rio_gwm_ui_image }}"
          secret: dockerhub
      register: user_interface_package_id
    - name: simulator package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: simulator
        present: "{{ present }}"
        package_from: manifest_path
        manifest_path: /tmp/simulator.json
        executables_info:
        - name: gzclient
          type: docker
          docker_image: "{{ rio_amr_pa_image }}"
          secret: dockerhub
        - name: gazebo
          type: docker
          docker_image: "{{ rio_amr_pa_image }}"
          secret: dockerhub
      register: simulator_package_id

- name: POSTGRES, GWM, UI, SIMULATOR Deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: POSTGRES Deployment
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_postgres"
        component_name: postgres
        present: "{{ present }}"
        package_name: postgres
        component_params:
          POSTGRES_DB: gwm_core
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      register: db_deploy_id
    - name: GWM deployment
      async: "{{ async_time | default('2000') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_gwm"
        component_name: core
        present: "{{ present }}"
        package_name: gwm
        depends:
          deployments:
            - "{{ prefix_name }}_postgres"
        component_params:
          AUTOBOOTSTRAP: "true"
          DEBUG: "true"
          DJANGO_LOG_LEVEL: WARNING
      register: gwm_deploy_id
    - name: AMR UI  deployment
      async: "{{ async_time | default('2600') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_amr_ui"
        component_name: amr_ui
        present: "{{ present }}"
        package_name: user_interface
        depends:
          deployments:
            - "{{ prefix_name }}_gwm"
        component_params:
          SKIP_PREFLIGHT_CHECK: "true"
          GWM_API_VERSION: v1
          DEFAULT_GWM_INTERFACE_HOST: gbc
          DEFAULT_GWM_INTERFACE_PORT: 8080
          DEFAULT_GWM_INTERFACE_PROTOCOL: ws
      register: amr_ui_deploy_id
    - name: Simulator  deployment
      async: "{{ async_time | default('2600') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_simulator"
        component_name: gazebo
        present: "{{ present }}"
        package_name: simulator
        depends:
          deployments:
            - "{{ prefix_name }}_gwm"
        component_params:
          AUTOBOOTSTRAP: "true"
          GWM_AUTH_TOKEN	: autobootstrap
          GWM_CORE_URL_PORT: 443
          ITEM: NONE
          ITEM_SPAWN_FROM: "{{ item_spawn_from }}"
          LEGACY_LOCALIZATION: "false"
          LOCALIZATION_MODE: managed
          LOCALIZATION_TYPE: amcl
          MAPPING_TYPE: gmapping
          PYTHONUNBUFFERED: 1
          SITE: "{{ site_name }}"
          VNC_PASSWORD: rapyuta
          VNC_RESOLUTION: 1280x720
      register: simulator_deploy_id


- name: Async wait on deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: "DB, GWM, AMR UI, SIMULATOR DEPLOYMENTS - check on async status"
      async_status:
        jid: "{{ item.ansible_job_id}}"
      register: amr_log
      until: amr_log.finished
      retries: 600
      delay: 20
      when:
        - ansible_async|bool == true
      loop:
      - "{{ db_deploy_id }}"
      - "{{ gwm_deploy_id }}"
      - "{{ amr_ui_deploy_id }}"
      - "{{ simulator_deploy_id }}"

    - name: dump test output
      debug:
        msg: '{{ item }}'
      when: ansible_async|bool == true
      loop:
      - "{{ db_deploy_id }}"
      - "{{ gwm_deploy_id }}"
      - "{{ amr_ui_deploy_id }}"
      - "{{ simulator_deploy_id }}"
