- name: Secrets, Networks, Static Routes
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - copy:
        src: rio_amr_pa.json
        dest: /tmp/rio_amr_pa.json
    - copy:
        src: rio_amr_ui.json
        dest: /tmp/rio_amr_ui.json
    - copy:
        src: rio_db.json
        dest: /tmp/rio_db.json
    - copy:
        src: rio_gazebo.json
        dest: /tmp/rio_gazebo.json
    - copy:
        src: rio_gbc.json
        dest: /tmp/rio_gbc.json
    - copy:
        src: rio_gwm.json
        dest: /tmp/rio_gwm.json
    - name: Docker Secret
      async: 100
      poll: 0
      rapyuta.rr_io.secrets:
        name: dockerhub
        present: "{{ present }}"
        type: docker
        username: dsatherr
        password: Funny#Fish
        email: dhananjay.sathe@rapyuta-robotics.
    - name: Docker Secret 2
      async: 100
      poll: 0
      rapyuta.rr_io.secrets:
        name: dockerhub2
        present: "{{ present }}"
        type: docker
        username: larryngrapyuta
        password: L1a9r8r8y*
        email: larry.ng@rapyuta-robotics.com
    - name: Network Deployment
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: native_network
        present: "{{ present }}"
        type: native_network
        ros_distro: melodic
        resource_type: small
    - name: GWM Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: rr-gwm
        present: "{{ present }}"
        type: static_route
    - name: GBC Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: rr-gbc
        present: "{{ present }}"
        type: static_route
    - name: AMR UI Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: amr-ui
        present: "{{ present }}"
        type: static_route
    - name: Gazebo UI Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: gazebo-ui
        present: "{{ present }}"
        type: static_route
    - name: rio_amr_pa package
      async: 1250
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_amr_pa
        present: "{{ present }}"
        type: docker
        build: rio_amr_pa
        docker_image: larryngrapyuta/testbuild:10_amr_test
        secret: dockerhub2
        manifest_path: /tmp/rio_amr_pa.json
      register: testout
    - name: rio_gwm_ui package
      async: 1000
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gwm_ui
        present: "{{ present }}"
        type: docker
        docker_image: rrdockerhub/rr_amr_ui:release_05_21
        build: rio_gwm_ui
        secret: dockerhub
        manifest_path: /tmp/rio_amr_ui.json
      register: testout
    - name: rio_db package
      async: 1000
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_db
        present: "{{ present }}"
        type: docker
        docker_image: rrdockerhub/rr_amr_postgres:nightly
        secret: dockerhub
        manifest_path: /tmp/rio_db.json
      register: testout
    - name: rio_gazebo package
      async: 1250
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gazebo
        present: "{{ present }}"
        type: docker
        docker_image: larryngrapyuta/testbuild:10_amr_test
        build: rio_amr_pa
        secret: dockerhub2
        manifest_path: /tmp/rio_gazebo.json
      register: testout
    - name: rio_gbc package
      async: 1250
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gbc
        present: "{{ present }}"
        type: docker
        docker_image: larryngrapyuta/testbuild:10_amr_test
        build: rio_amr_pa
        secret: dockerhub2
        manifest_path: /tmp/rio_gbc.json
      register: testout
    - name: rio_gwm package
      async: 1000
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gwm
        present: "{{ present }}"
        type: docker
        docker_image: rrdockerhub/rr_amr_gwm:release_05_21
        build: rio_gwm
        secret: dockerhub
        manifest_path: /tmp/rio_gwm.json
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
- name: DB, GWM, GBC, AMR UI Deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: DB Deployment
      async: 100
      poll: 0
      rapyuta.rr_io.deployments:
        name: postgres
        component_name: postgres
        present: "{{ present }}"
        package_name: rio_db
        component_params:
          POSTGRES_DB: gwm_core
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      register: testout
    - name: GWM deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: rr_gwm
        component_name: core
        present: "{{ present }}"
        package_name: rio_gwm
        depends:
          deployments:
            - postgres
        networks:
          static_routes:
            - name: rr-gwm
              endpoint_name: GWM_CORE_URL
        component_params:
          AUTOBOOTSTRAP: true
          DEBUG: true
          DJANGO_LOG_LEVEL: WARNING
      register: testout
    - name: GBC deployment
      async: 2200
      poll: 0
      rapyuta.rr_io.deployments:
        name: rr_gbc
        component_name: gbc
        present: "{{ present }}"
        package_name: rio_gbc
        depends:
          deployments:
            - postgres
            - rr_gwm
        networks:
          static_routes:
            - name: rr-gbc
              endpoint_name: GWM_INTERFACE_ENDPOINT
          native_networks:
            - name: native_network
        component_params:
          GWM_INTERFACE_SITE: tatsumi
          AUTOBOOTSTRAP: true
          GWM_INTERFACE_ORG_ID: 1
          GWM_AUTH_TOKEN: autobootstrap
          IO_AMR_GWM_INTERFACE_NODE_NAME: rr_gwm_interface
          ROSCONSOLE_FORMAT: "[$${severity}] [$${time}] [$${node} $${logger} $${function} $${line}]: $${message}"
      register: testout
    - name: AMR UI  deployment
      async: 2600
      poll: 0
      rapyuta.rr_io.deployments:
        name: amr_ui
        component_name: gwm-ui
        present: "{{ present }}"
        package_name: rio_gwm_ui
        depends:
          deployments:
            - rr_gwm
            - rr_gbc
        networks:
          static_routes:
            - name: amr-ui
              endpoint_name: GWM_UI
        component_params:
          SKIP_PREFLIGHT_CHECK: true
          GWM_API_VERSION: v1
          DEFAULT_GWM_INTERFACE_HOST: gbc
          DEFAULT_GWM_INTERFACE_PORT: 8080
          DEFAULT_GWM_INTERFACE_PROTOCOL: ws
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
- name: Gazebo and AMR deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: Gazebo Deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: gazebo
        component_name: gazebo
        component_alias: gazebo
        present: "{{ present }}"
        package_name: rio_gazebo
        networks:
          static_routes:
            - name: gazebo-ui
              endpoint_name: VNC_EP
          native_networks:
            - name: native_network
        component_params:
          VNC_PASSWORD: rapyuta
          VNC_RESOLUTION: 1920x1080
          DEBUG: true
          RACK: true
          WORLD: tatsumi
          ITEM_SPAWN_FROM: AUTO
          GWM_AUTH_TOKEN: autobootstrap
    - name: AMR Deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: "amr{{ item.id }}"
        component_name: amr
        component_alias: "amr{{ item.id }}"
        present: "{{ present }}"
        package_name: rio_amr_pa
        networks:
          native_networks:
            - name: native_network
        component_params:
          ROBOT_MODEL: rr_pa_amr
          ROBOT_NAV_MODEL: rr_pa_amr
          NAV_STRATEGY: graph_guided
          MAP: tatsumi
          MAP_ID: 1
          WORLD2MAP_X: 0
          WORLD2MAP_Y: 0
          WORLD2MAP_Z: 0
          WORLD2MAP_YAW: 0
          IDLE_TIMEOUT: 1000000
          AGENT_ID: "{{ item.id }}"
          X_POS: "{{ item.x }}"
          Y_POS: "{{ item.y }}"
          Z_POS: 0.0
          YAW: 1.57
      loop:
        - {id: '1', x: '6.2', y: '12'}
        - {id: '2', x: '11', y: '12'}
        - {id: '3', x: '13.6', y: '1.3'}
        - {id: '4', x: '21.9', y: '11.2'}
        - {id: '5', x: '1.4', y: '3.5'}
        - {id: '6', x: '14.4', y: '9.4'}
        - {id: '7', x: '15.4', y: '5.9'}
        - {id: '8', x: '16.5', y: '2.9'}
        - {id: '9', x: '5.8', y: '6.9'}
        - {id: '10', x: '8.4', y: '12'}
      register: amr_id
    - name: "AMR - check on async status"
      async_status:
        jid: "{{ item.ansible_job_id}}"
      register: amr_log
      until: amr_log.finished
      retries: 60
      delay: 20
      when: "{{ present }}"
      with_items: "{{ amr_id.results }}"
    - name: dump test output
      debug:
        msg: '{{ item }}'
      with_items: "{{ amr_id.results }}"
#    - name: "wait for UI to come up"
#      uri:
#        url: "https://rr-gwm-kqdbp.ep-r.io/v1/site/1"
#        method: GET
#        headers:
#          accept: "application/json"
#          X-RRAMR-Org: "1"
#          Authorization: "token autobootstrap"
#        status_code: 200
#      when: "{{ present }}"
#      register: result
#      until: result.status == 200
#      retries: 60
#      delay: 20
#    - name: "Pause to wait for UI to finish building"
#      wait_for:
#        timeout: 60
#      when: "{{ present }}"
#    - name: "Adding Agents to db"
#      uri:
#        url: "https://rr-gwm-kqdbp.ep-r.io/v1/agent"
#        method: POST
#        headers:
#          accept: "application/json"
#          X-RRAMR-Org: "1"
#          X-RRAMR-Site: "1"
#          Authorization: "token autobootstrap"
#        body: '{"id": {{ item }}, "name": "agent{{ item }}", "robot_id": {{ item }}, "robot_descriptor_id": {{ item }}, "map": 1}'
#        body_format: json
#        status_code:
#          - "200"
#          - "201"
#          - "409"
#      when: "{{ present }}"
#      with_sequence: 1-10


