- name: Secrets, Networks, Static Routes
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    ### Generate package manifest files
    - name: update package manifest files
      tags: [ "always" ]
      template:
        src: ./{{item}}.json.j2
        dest: /tmp/{{item}}.json
      with_items: [ "rio_amr_pa", "rio_gbc" ]

    ### Copy package manifest files
    - name: Copy package manifest files
      tags: [ "always" ]
      copy:
        src: "{{item}}.json"
        dest: "/tmp/{{item}}.json"
      with_items: [ "rio_amr_ui", "rio_db", "rio_gazebo", "rio_gwm" ]
 
    ### Regsiter DockerHub secret key
    - name: DockerHub Secret
      tags: [ "always" ]
      async: 100
      poll: 0
      rapyutarobotics.rr_io.secrets:
        name: dockerhub
        present: "{{ present }}"
        type: docker
        username: "{{ dockerhub_read_user }}"
        password: "{{ dockerhub_read_password }}"
        email: rss2.admin@rapyuta-robotics.com

    ### Add native or routed network
    - name: Network Deployment
      tags: [ "always" ]
      async: 100
      poll: 0
      rapyutarobotics.rr_io.networks:
        name: "{{ deployment_prefix }}_{{item.type}}"
        type: "{{item.type}}"
        present: "{{ present }}"
        ros_distro: melodic
        resource_type: small
      when: "{{item.is_routed}}"
      with_items:
        - { type: native_network, is_routed: routed_network|bool == false }
        - { type: routed_network, is_routed: routed_network|bool == true }

    ### Add static routes
    - name: Add Static Routes
      tags: [ "always" ]
      async: 100
      poll: 0
      rapyutarobotics.rr_io.networks:
        name: "{{ item }}"
        present: "{{ present }}"
        type: static_route
      with_items:
        - "{{ deployment_prefix }}-gwm"
        - "{{ deployment_prefix }}-gbc"
        - "{{ deployment_prefix }}-amr-ui"
        - "{{ deployment_prefix }}-gazebo-ui"

    ### Build packages
    - name: Build Packages
      tags: [ "always" ]
      async: 1250
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: "{{ item.name }}"
        present: "{{ present }}"
        type: docker
        build: "{{ item.build }}"
        docker_image: "{{ item.docker_image }}"
        secret: dockerhub
        manifest_path: "/tmp/{{ item.manifest }}.json"
      with_items:
        - { name: rio_amr_pa, build: rio_amr_pa, manifest: rio_amr_pa, docker_image: "{{ BUILD.PA.DOCKER_IMAGE }}" }
        - { name: rio_gwm_ui, build: rio_gwm_ui, manifest: rio_amr_ui, docker_image: "{{ BUILD.AMR_UI.DOCKER_IMAGE }}" }
        - { name: rio_db,     build: rio_db,     manifest: rio_db,     docker_image: "{{ BUILD.DB.DOCKER_IMAGE }}" }
        - { name: rio_gazebo, build: rio_amr_pa, manifest: rio_gazebo, docker_image: "{{ BUILD.PA.DOCKER_IMAGE }}" }
        - { name: rio_gbc,    build: rio_amr_pa, manifest: rio_gbc,    docker_image: "{{ BUILD.PA.DOCKER_IMAGE }}" }
        - { name: rio_gwm,    build: rio_gwm,    manifest: rio_gwm,    docker_image: "{{ BUILD.GWM.DOCKER_IMAGE }}" }

- name: DB, GWM, GBC, AMR UI Deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    ### DB Deployment
    - name: DB Deployment
      tags: [ "always" ]
      async: 100
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ deployment_prefix }}_postgres"
        component_name: postgres
        present: "{{ present }}"
        package_name: rio_db
        component_params: "{{ DB_PARAMS }}"
      register: db_deploy_id

    ### GWM Deployment
    - name: GWM deployment
      tags: [ "always" ]
      async: 2000
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ deployment_prefix }}_rr_gwm"
        component_name: core
        present: "{{ present }}"
        package_name: rio_gwm
        depends:
          deployments:
            - "{{ deployment_prefix }}_postgres"
        networks:
          static_routes:
            - name: "{{ deployment_prefix }}-gwm"
              endpoint_name: GWM_CORE_URL
        component_params: "{{GWM_PARAMS}}"
      register: rr_gwm_deploy_id

    ### GBC Deployment
    - name: GBC deployment (Native Network)
      tags: [ "always" ]
      async: 2200
      poll: 0
      rapyutarobotics.rr_io.deployments: &gbc_deployment
        name: "{{ deployment_prefix }}_rr_gbc"
        component_name: gbc
        present: "{{ present }}"
        package_name: rio_gbc
        depends:
          deployments:
            - "{{ deployment_prefix }}_postgres"
            - "{{ deployment_prefix }}_rr_gwm"
        networks:
          static_routes:
            - name: "{{ deployment_prefix }}-gbc"
              endpoint_name: GWM_INTERFACE_ENDPOINT
          native_networks:
            - name: "{{ deployment_prefix }}_native_network"
        component_params: "{{GBC_PARAMS}}"
      when: routed_network|bool == false
      register: rr_gbc_deploy_id
    - name: GBC deployment (Routed Network)
      tags: [ "always" ]
      async: 2200
      poll: 0
      rapyutarobotics.rr_io.deployments:
        <<: *gbc_deployment
        networks:
          static_routes:
            - name: "{{ deployment_prefix }}-gbc"
              endpoint_name: GWM_INTERFACE_ENDPOINT
          routed_networks:
            - name: "{{ deployment_prefix }}_routed_network"
      when: routed_network|bool == true
      register: rr_gbc_deploy_id

    ### AMR UI Deployment
    - name: AMR UI deployment
      tags: [ "always" ]
      async: 2600
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ deployment_prefix }}_amr_ui"
        component_name: gwm-ui
        present: "{{ present }}"
        package_name: rio_gwm_ui
        depends:
          deployments:
            - "{{ deployment_prefix }}_rr_gwm"
            - "{{ deployment_prefix }}_rr_gbc"
        networks:
          static_routes:
            - name: "{{ deployment_prefix }}-amr-ui"
              endpoint_name: GWM_UI
        component_params: "{{AMR_UI_PARAMS}}"
      register: amr_ui_deploy_id

- name: Gazebo and AMR deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    ### Gazebo Deployment
    - name: Gazebo Deployment (Native Network)
      tags: [ "always" ]
      async: 2000
      poll: 0
      rapyutarobotics.rr_io.deployments: &gazebo_deployment
        name: "{{ deployment_prefix }}_gazebo"
        component_name: gazebo
        component_alias: gazebo
        present: "{{ present }}"
        package_name: rio_gazebo
        networks:
          static_routes:
            - name: "{{ deployment_prefix }}-gazebo-ui"
              endpoint_name: VNC_EP
          native_networks:
            - name: "{{ deployment_prefix }}_native_network"
        component_params: "{{GAZEBO_PARAMS}}"
      when: routed_network|bool == false
      register: gazebo_native_deploy_id
    - name: Gazebo Deployment (Routed Network)
      tags: [ "always" ]
      async: 2000
      poll: 0
      rapyutarobotics.rr_io.deployments:
        <<: *gazebo_deployment
        networks:
          static_routes:
            - name: "{{ deployment_prefix }}-gazebo-ui"
              endpoint_name: VNC_EP
          routed_networks:
            - name: "{{ deployment_prefix }}_routed_network"
      when: routed_network|bool == true
      register: gazebo_routed_deploy_id

    ### AMR Deployment
    - name: AMR Deployment (Native Network)
      tags: [ "always" ]
      async: 2000
      poll: 0
      rapyutarobotics.rr_io.deployments: &amr_deployment
        name: "{{ deployment_prefix }}_amr{{ item.AGENT_ID }}"
        component_name: amr
        component_alias: "amr{{ item.AGENT_ID }}"
        present: "{{ present }}"
        package_name: rio_amr_pa
        networks:
          native_networks:
            - name: "{{ deployment_prefix }}_native_network"
        component_params: "{{item}}"
      when: routed_network|bool == false
      loop: "{{  AMR_PARAMS  }}"
      register: amr_native_deploy_id
    - name: AMR Deployment (Routed Network)
      tags: [ "always" ]
      async: 2000
      poll: 0
      rapyutarobotics.rr_io.deployments:
        <<: *amr_deployment
        networks:
          routed_networks:
            - name: "{{ deployment_prefix }}_routed_network"
      when: routed_network|bool == true
      loop: "{{  AMR_PARAMS  }}"
      register: amr_routed_deploy_id

- name: AMR, AMR UI, GAZEBO - Check on async status
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    ### Check on async status
    - name: "Check on async status (Native Network)"
      tags: [ "always" ]
      async_status:
        jid: "{{ item.ansible_job_id}}"
      register: amr_log
      until: amr_log.finished
      retries: 60
      delay: 20
      when:
        - "{{ present }}"
        - routed_network|bool == false
      with_items:
        - "{{ amr_native_deploy_id.results }}"
        - "{{ gazebo_native_deploy_id }}"
        - "{{ amr_ui_deploy_id }}"
    - name: "Check on async status (Routed Network)"
      tags: [ "always" ]
      async_status:
        jid: "{{ item.ansible_job_id}}"
      register: amr_log
      until: amr_log.finished
      retries: 60
      delay: 20
      when:
        - "{{ present }}"
        - routed_network|bool == true
      with_items:
        - "{{ amr_routed_deploy_id.results }}"
        - "{{ gazebo_routed_deploy_id }}"
        - "{{ amr_ui_deploy_id }}"
