- name: Playbook Sanity checks and configuration
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: Test if the type of 'prefix_name' is string
      assert:
        that:
          - prefix_name is regex("^[a-zA-Z0-9\-]*$")
          - prefix_name != "prefix"
        fail_msg: prefix_name is not alphanumeric or is using the default 'prefix' name, please fix the prefix_name and try again
    - name: Test if docker username and password are still default vaules
      assert:
        that:
          - docker_user  != "insert username"
          - docker_password != "insert password"
        fail_msg: docker username or password is currently set as default values, please check both and try again
    - name: set_async_status
      set_fact:
        async_time: 0
      when: ansible_async|bool == false

- name: Secrets, Networks
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: Docker Secret
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.secrets:
        name: dockerhub
        present: "{{ present }}"
        type: docker
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        email: rss2.admin@rapyuta-robotics.com
      register: docker_secret_id
    - name: Native Network Deployment
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.networks:
        name: "{{ prefix_name }}_native_network"
        present: "{{ present }}"
        type: native_network
        ros_distro: melodic
        runtime: device
        device_name: "{{ device_name }}"
        network_interface: "{{ device_network_interface }}"
        resource_type: small
      when: routed_network|bool == false
      register: native_network_id
    - name: Routed Network Deployment
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.networks:
        name: "{{ prefix_name }}_routed_network"
        present: "{{ present }}"
        type: routed_network
        runtime: cloud
        ros_distro: melodic
        resource_type: small
      when: routed_network|bool == true
      register: routed_network_id

- name: DB, GWM, AMR UI, AMR, SERVER Packages
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: rio_db package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: rio_db
        present: "{{ present }}"
        package_from: io_project
        source_io_project_info:
          project_id: "{{ source_project_id }}"
          auth_token: "{{ source_auth_token }}"
          package_name: postgres
          package_version: max
        executables_info:
        - name: pgsql
          type: docker
          docker_image: "{{ rio_db_image }}"
      register: rio_db_package_id
    - name: rio_gwm package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: rio_gwm
        present: "{{ present }}"
        package_from: io_project
        source_io_project_info:
          project_id: "{{ source_project_id }}"
          auth_token: "{{ source_auth_token }}"
          package_name: gwm
          package_version: max
        executables_info:
        - name: core
          type: docker
          docker_image: "{{ rio_gwm_image }}"
          secret: dockerhub
      register: rio_gwm_package_id
    - name: rio_gwm_ui package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: rio_gwm_ui
        present: "{{ present }}"
        package_from: io_project
        source_io_project_info:
          project_id: "{{ source_project_id }}"
          auth_token: "{{ source_auth_token }}"
          package_name: amr_ui
          package_version: max
        executables_info:
        - name: core
          type: docker
          docker_image: "{{ rio_gwm_ui_image }}"
          secret: dockerhub
      register: rio_gwm_ui_package_id
    - name: rio_amr package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: device_amr
        present: "{{ present }}"
        package_from: io_project
        source_io_project_info:
          project_id: "{{ source_project_id }}"
          auth_token: "{{ source_auth_token }}"
          package_name: amr
          package_version: max
        executables_info:
        - name: amr
          type: docker
          docker_image: "{{ rio_amr_pa_image }}"
          secret: dockerhub
      register: rio_amr_package_id
    - name: rio_server package
      async: "{{ async_time | default('1000') }}"
      poll: 0
      rapyutarobotics.rr_io.packages:
        version: auto
        name: rio_server
        present: "{{ present }}"
        package_from: io_project
        source_io_project_info:
          project_id: "{{ source_project_id }}"
          auth_token: "{{ source_auth_token }}"
          package_name: server
          package_version: max
        executables_info:
        - name: gbc
          type: docker
          docker_image: "{{ rio_amr_pa_image }}"
          secret: dockerhub
        - name: tracing_agent
          type: docker
          docker_image: "{{ tracing_agent_image }}"
      register: rio_server_package_id

- name: DB, GWM, AMR UI, AMR, SERVER Deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: DB Deployment
      async: "{{ async_time | default('100') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_postgres"
        component_name: postgres
        present: "{{ present }}"
        package_name: rio_db
        runtime: device
        device_name: "{{ device_name }}"
        component_params:
          POSTGRES_DB: gwm_core
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      register: db_deploy_id
    - name: GWM deployment
      async: "{{ async_time | default('2000') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_gwm"
        component_name: core
        present: "{{ present }}"
        package_name: rio_gwm
        runtime: device
        device_name: "{{ device_name }}"
        depends:
          deployments:
            - "{{ prefix_name }}_postgres"
        component_params:
          AUTOBOOTSTRAP: "true"
          DEBUG: "true"
          DJANGO_LOG_LEVEL: WARNING
      register: gwm_deploy_id
    - name: AMR UI  deployment
      async: "{{ async_time | default('2600') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_amr_ui"
        component_name: amr_ui
        present: "{{ present }}"
        package_name: rio_gwm_ui
        runtime: device
        device_name: "{{ device_name }}"
        depends:
          deployments:
            - "{{ prefix_name }}_gwm"
        component_params:
          SKIP_PREFLIGHT_CHECK: "true"
          GWM_API_VERSION: v1
          DEFAULT_GWM_INTERFACE_PORT: 8080
          DEFAULT_GWM_INTERFACE_PROTOCOL: ws
      register: amr_ui_deploy_id
    - name: AMR  deployment
      async: "{{ async_time | default('2600') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_amr"
        component_name: amr
        present: "{{ present }}"
        package_name: device_amr
        runtime: device
        device_name: "{{ device_name }}"
        networks:
          native_networks:
            - name: "{{ prefix_name }}_native_network"
        depends:
          deployments:
            - "{{ prefix_name }}_gwm"
      register: amr_deploy_id
    - name: SERVER  deployment
      async: "{{ async_time | default('2600') }}"
      poll: 0
      rapyutarobotics.rr_io.deployments:
        name: "{{ prefix_name }}_server"
        component_name: gbc
        present: "{{ present }}"
        package_name: rio_server
        runtime: device
        device_name: "{{ device_name }}"
        networks:
          native_networks:
            - name: "{{ prefix_name }}_native_network"
        depends:
          deployments:
            - "{{ prefix_name }}_gwm"
      register: server_deploy_id


- name: Async wait on deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: "DB, GWM, AMR UI, SIMULATOR DEPLOYMENTS - check on async status"
      async_status:
        jid: "{{ item.ansible_job_id}}"
      register: amr_log
      until: amr_log.finished
      retries: 600
      delay: 20
      when:
        - ansible_async|bool == true
      loop:
      - "{{ db_deploy_id }}"
      - "{{ gwm_deploy_id }}"
      - "{{ amr_ui_deploy_id }}"
      - "{{ amr_deploy_id }}"
      - "{{ server_deploy_id }}"

    - name: dump test output
      debug:
        msg: '{{ item }}'
      when: ansible_async|bool == true
      loop:
      - "{{ db_deploy_id }}"
      - "{{ gwm_deploy_id }}"
      - "{{ amr_ui_deploy_id }}"
      - "{{ amr_deploy_id }}"
      - "{{ server_deploy_id }}"