- name: Secrets, Networks, Static Routes
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - copy:
        src: rio_amr_pa.json
        dest: /tmp/rio_amr_pa.json
    - copy:
        src: rio_amr_ui.json
        dest: /tmp/rio_amr_ui.json
    - copy:
        src: rio_db.json
        dest: /tmp/rio_db.json
    - copy:
        src: rio_gazebo.json
        dest: /tmp/rio_gazebo.json
    - copy:
        src: rio_gbc.json
        dest: /tmp/rio_gbc.json
    - copy:
        src: rio_gwm.json
        dest: /tmp/rio_gwm.json
    - name: Network Deployment
      async: 12000
      poll: 0
      abhinavg97.rr_io.networks:
        name: "{{ prefix_name }}_native_network"
        present: "{{ present }}"
        type: native_network
        ros_distro: melodic
        resource_type: small
      register: native_network_id
    - name: GWM Static Route
      async: 12000
      poll: 0
      abhinavg97.rr_io.networks:
        name: "{{ prefix_name }}-gwm"
        present: "{{ present }}"
        type: static_route
      register: gwm_static_route_id
    - name: GBC Static Route
      async: 12000
      poll: 0
      abhinavg97.rr_io.networks:
        name: "{{ prefix_name }}-gbc"
        present: "{{ present }}"
        type: static_route
      register: gbc_static_route_id
    - name: AMR UI Static Route
      async: 12000
      poll: 0
      abhinavg97.rr_io.networks:
        name: "{{ prefix_name }}-amr-ui"
        present: "{{ present }}"
        type: static_route
      register: amr_ui_static_route_id
    - name: rio_amr_pa package
      async: 12000
      poll: 0
      abhinavg97.rr_io.packages:
        name: "{{ prefix_name }}_rio_amr_pa"
        present: "{{ present }}"
        type: docker
        docker_image: "{{ rio_amr_pa_image }}"
        secret: "docker"
        manifest_path: /tmp/rio_amr_pa.json
      register: rio_amr_pa_package_id
    - name: rio_amr_pa_hw package
      async: 12000
      poll: 0
      abhinavg97.rr_io.packages:
        name: "{{ prefix_name }}_rio_amr_pa_hw"
        present: "{{ present }}"
        type: docker
        docker_image: "{{ rio_amr_pa_hw_image }}"
        secret: "docker"
        manifest_path: /tmp/rio_amr_pa.json
      register: rio_amr_pa_hw_package_id
    - name: rio_gwm_ui package
      async: 12000
      poll: 0
      abhinavg97.rr_io.packages:
        name: "{{ prefix_name }}_rio_gwm_ui"
        present: "{{ present }}"
        type: docker
        docker_image: "{{ rio_gwm_ui_image }}"
        secret: "docker"
        manifest_path: /tmp/rio_amr_ui.json
      register: rio_gwm_ui_package_id
    - name: rio_db package
      async: 12000
      poll: 0
      abhinavg97.rr_io.packages:
        name: "{{ prefix_name }}_rio_db"
        present: "{{ present }}"
        type: docker
        docker_image: "rrdockerhub/rr_amr_postgres:nightly"
        secret: "docker"
        manifest_path: /tmp/rio_db.json
      register: rio_db_package_id
    - name: rio_gbc package
      async: 12000
      poll: 0
      abhinavg97.rr_io.packages:
        name: "{{ prefix_name }}_rio_gbc"
        present: "{{ present }}"
        type: docker
        docker_image: "{{ rio_amr_pa_image }}"
        secret: "docker"
        manifest_path: /tmp/rio_gbc.json
      register: rio_gbc_package_id
    - name: rio_gwm package
      async: 12000
      poll: 0
      abhinavg97.rr_io.packages:
        name: "{{ prefix_name }}_rio_gwm"
        present: "{{ present }}"
        type: docker
        docker_image: "{{ rio_gwm_image }}"
        secret: "docker"
        manifest_path: /tmp/rio_gwm.json
      register: rio_gwm_package_id
- name: DB, GWM, GBC, AMR UI Deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: DB Deployment
      async: 12000
      poll: 0
      abhinavg97.rr_io.deployments:
        name: "{{ prefix_name }}_postgres"
        component_name: postgres
        present: "{{ present }}"
        package_name: "{{ prefix_name }}_rio_db"
        component_params:
          POSTGRES_DB: gwm_core
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      register: db_deploy_id
    - name: GWM deployment
      async: 12000
      poll: 0
      abhinavg97.rr_io.deployments:
        name: "{{ prefix_name }}_rr_gwm"
        component_name: core
        present: "{{ present }}"
        package_name: "{{ prefix_name }}_rio_gwm"
        depends:
          deployments:
            - "{{ prefix_name }}_postgres"
        networks:
          static_routes:
            - name: "{{ prefix_name }}-gwm"
              endpoint_name: GWM_CORE_URL
        component_params:
          AUTOBOOTSTRAP: true
          DEBUG: true
          DJANGO_LOG_LEVEL: WARNING
      register: rr_gwm_deploy_id
    - name: GBC deployment
      async: 12000
      poll: 0
      abhinavg97.rr_io.deployments:
        name: "{{ prefix_name }}_rr_gbc"
        component_name: gbc
        present: "{{ present }}"
        package_name: "{{ prefix_name }}_rio_gbc"
        depends:
          deployments:
            - "{{ prefix_name }}_postgres"
            - "{{ prefix_name }}_rr_gwm"
        networks:
          static_routes:
            - name: "{{ prefix_name }}-gbc"
              endpoint_name: GWM_INTERFACE_ENDPOINT
          native_networks:
            - name: "{{ prefix_name }}_native_network"
        component_params:
          GWM_INTERFACE_SITE: tatsumi
          AUTOBOOTSTRAP: true
          GWM_INTERFACE_ORG_ID: 1
          GWM_AUTH_TOKEN: autobootstrap
          IO_AMR_GWM_INTERFACE_NODE_NAME: rr_gwm_interface
          ROSCONSOLE_FORMAT: "[$${severity}] [$${time}] [$${node} $${logger} $${function} $${line}]: $${message}"
      register: rr_gbc_deploy_id
    - name: AMR UI  deployment
      async: 12000
      poll: 0
      abhinavg97.rr_io.deployments:
        name: "{{ prefix_name }}_amr_ui"
        component_name: gwm-ui
        present: "{{ present }}"
        package_name: "{{ prefix_name }}_rio_gwm_ui"
        depends:
          deployments:
            - "{{ prefix_name }}_rr_gwm"
            - "{{ prefix_name }}_rr_gbc"
        networks:
          static_routes:
            - name: "{{ prefix_name }}-amr-ui"
              endpoint_name: GWM_UI
        component_params:
          SKIP_PREFLIGHT_CHECK: true
          GWM_API_VERSION: v1
          DEFAULT_GWM_INTERFACE_HOST: gbc
          DEFAULT_GWM_INTERFACE_PORT: 8080
          DEFAULT_GWM_INTERFACE_PROTOCOL: ws
      register: amr_ui_deploy_id
- name: Gazebo and AMR deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: AMR Deployment
      async: 12000
      poll: 0
      abhinavg97.rr_io.deployments:
        name: "sbm_2"
        type: "device"
        device_name: "sbm_2"
        component_name: amr
        component_alias: "sbm_2"
        present: "{{ present }}"
        package_name: "{{ prefix_name }}_rio_amr_pa_hw"
        networks:
          native_networks:
            - name: "{{ prefix_name }}_native_network"
        component_params:
          ROBOT_MODEL: rr_pa_amr
          ROBOT_NAV_MODEL: rr_pa_amr
          NAV_STRATEGY: graph_guided
          MAP: tatsumi
          MAP_ID: 1
          WORLD2MAP_X: 0
          WORLD2MAP_Y: 0
          WORLD2MAP_Z: 0
          WORLD2MAP_YAW: 0
          IDLE_TIMEOUT: 1000000
          AGENT_ID: "{{ item.id }}"
          X_POS: "{{ item.x }}"
          Y_POS: "{{ item.y }}"
          Z_POS: 0.0
          YAW: 1.57
      loop:
        - { id: '1', x: '6.2', y: '12'}
      register: amr_id
    - name: "AMR - check on async status"
      async_status:
        jid: "{{ item.ansible_job_id}}"
      register: amr_log
      until: amr_log.finished
      retries: 600
      delay: 20
      when: "{{ present }}"
      with_items: "{{ amr_id.results }}"
    - name: dump amr async output
      debug:
        msg: '{{ item }}'
      with_items: "{{ amr_id.results }}"
    - name: "rr_gwm deployment - check on async status"
      async_status:
        jid: "{{ rr_gwm_deploy_id.ansible_job_id }}"
      register: amr_log
      until: amr_log.finished
      retries: 600
      delay: 20
    - name: "wait for UI to come up"
      uri:
        url: "https://{{ prefix_name }}-gwm-kqdbp.ep-r.io/v1/site/1"
        method: GET
        headers:
          accept: "application/json"
          X-RRAMR-Org: "1"
          Authorization: "token autobootstrap"
        status_code: 200
      when: "{{ present }}"
      register: result
      until: result.status == 200
      retries: 600
      delay: 20
    - name: "Pause to wait for UI to finish building"
      wait_for:
        timeout: 60
      when: "{{ present }}"
