- name: Secrets, Networks, Static Routes
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - copy:
        src: rio_amr_pa.json
        dest: /tmp/rio_amr_pa.json
    - copy:
        src: rio_amr_ui.json
        dest: /tmp/rio_amr_ui.json
    - copy:
        src: rio_db.json
        dest: /tmp/rio_db.json
    - copy:
        src: rio_gazebo.json
        dest: /tmp/rio_gazebo.json
    - copy:
        src: rio_gbc.json
        dest: /tmp/rio_gbc.json
    - copy:
        src: rio_gwm.json
        dest: /tmp/rio_gwm.json
    - name: Network Deployment
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: native_network
        present: false
        type: native_network
        ros_distro: melodic
        resource_type: small
    - name: GWM Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: rr-gwm
        present: false
        type: static_route
    - name: GBC Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: rr-gbc
        present: false
        type: static_route
    - name: AMR UI Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: amr-ui
        present: false
        type: static_route
    - name: Gazebo UI Static Route
      async: 100
      poll: 0
      rapyuta.rr_io.networks:
        name: gazebo-ui
        present: false
        type: static_route
    - name: rio_amr_pa build
      async: 100
      poll: 0
      rapyuta.rr_io.builds:
        name: rio_amr_pa
        strategy_type: docker
        present: false
        repository: git@github.com:rapyuta-robotics/io_amr.git
        branch: release
        docker_file_path: docker/amrrobot/Dockerfile
        source_secret: github
        docker_pull_secret: dockerhub
        docker_push_secret: dockerhub
        docker_image_repository: docker.io/rrdockerhub/io_amr_pa
        trigger: false
        trigger_name: ansible_ci
        tag_name: ansible_ci
    - name: rio_gwm_ui build
      async: 100
      poll: 0
      rapyuta.rr_io.builds:
        name: rio_gwm_ui
        strategy_type: docker
        present: false
        repository: git@github.com:rapyuta-robotics/io_amr.git
        context_directory: rr_amr_ui
        branch: release
        docker_file_path: Dockerfile
        source_secret: github
        docker_pull_secret: dockerhub
        docker_push_secret: dockerhub
        docker_image_repository: docker.io/rrdockerhub/rr_amr_ui
        trigger: false
        trigger_name: ansible_ci
        tag_name: ansible_ci
    - name: rio_gwm build
      async: 100
      poll: 0
      rapyuta.rr_io.builds:
        name: rio_gwm
        strategy_type: docker
        present: false
        repository: git@github.com:rapyuta-robotics/io_amr.git
        context_directory: rr_amr_gwm/gwm_core
        branch: release
        docker_file_path: Dockerfile.full
        source_secret: github
        docker_pull_secret: dockerhub
        docker_push_secret: dockerhub
        docker_image_repository: docker.io/rrdockerhub/rr_amr_gwm
        trigger: false
        trigger_name: ansible_ci
        tag_name: ansible_ci
    - name: rio_amr_pa package
      async: 1250
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_amr_pa
        present: false
        type: docker
        build: rio_amr_pa
        docker_image: rrdockerhub/io_amr_pa:release_04_27
        secret: dockerhub
        manifest_path: /tmp/rio_amr_pa.json
      register: testout
    - name: rio_gwm_ui package
      async: 1000
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gwm_ui
        present: false
        type: docker
        docker_image: rrdockerhub/rr_amr_ui:release_04_27
        build: rio_gwm_ui
        secret: dockerhub
        manifest_path: /tmp/rio_amr_ui.json
      register: testout
    - name: rio_db package
      async: 1000
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_db
        present: false
        type: docker
        docker_image: rrdockerhub/rr_amr_postgres:nightly
        secret: dockerhub
        manifest_path: /tmp/rio_db.json
      register: testout
    - name: rio_gazebo package
      async: 1250
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gazebo
        present: false
        type: docker
        docker_image: rrdockerhub/io_amr_pa:release_04_27
        build: rio_amr_pa
        secret: dockerhub
        manifest_path: /tmp/rio_gazebo.json
      register: testout
    - name: rio_gbc package
      async: 1250
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gbc
        present: false
        type: docker
        docker_image: rrdockerhub/io_amr_pa:release_04_27
        build: rio_amr_pa
        secret: dockerhub
        manifest_path: /tmp/rio_gbc.json
      register: testout
    - name: rio_gwm package
      async: 1000
      poll: 0
      rapyuta.rr_io.packages:
        name: rio_gwm
        present: false
        type: docker
        docker_image: rrdockerhub/rr_amr_gwm:release_04_27
        build: rio_gwm
        secret: dockerhub
        manifest_path: /tmp/rio_gwm.json
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
- name: DB, GWM, GBC, AMR UI Deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: DB Deployment
      async: 100
      poll: 0
      rapyuta.rr_io.deployments:
        name: postgres
        component_name: postgres
        present: false
        package_name: rio_db
        component_params:
          POSTGRES_DB: gwm_core
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      register: testout
    - name: GWM deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: rr_gwm
        component_name: core
        present: false
        package_name: rio_gwm
        depends:
          deployments:
            - postgres
        networks:
          static_routes:
            - name: rr-gwm
              endpoint_name: GWM_CORE_URL
        component_params:
          AUTOBOOTSTRAP: true
          DEBUG: true
          DJANGO_LOG_LEVEL: WARNING
      register: testout
    - name: GBC deployment
      async: 2200
      poll: 0
      rapyuta.rr_io.deployments:
        name: rr_gbc
        component_name: gbc
        present: false
        package_name: rio_gbc
        depends:
          deployments:
            - postgres
            - rr_gwm
        networks:
          static_routes:
            - name: rr-gbc
              endpoint_name: GWM_INTERFACE_ENDPOINT
          native_networks:
            - name: native_network
        component_params:
          GWM_INTERFACE_SITE: tatsumi
          AUTOBOOTSTRAP: true
          GWM_INTERFACE_ORG_ID: 1
          GWM_AUTH_TOKEN: autobootstrap
          IO_AMR_GWM_INTERFACE_NODE_NAME: rr_gwm_interface
          ROSCONSOLE_FORMAT: "[$${severity}] [$${time}] [$${node} $${logger} $${function} $${line}]: $${message}"
      register: testout
    - name: AMR UI  deployment
      async: 2600
      poll: 0
      rapyuta.rr_io.deployments:
        name: amr_ui
        component_name: gwm-ui
        present: false
        package_name: rio_gwm_ui
        depends:
          deployments:
            - rr_gwm
            - rr_gbc
        networks:
          static_routes:
            - name: amr-ui
              endpoint_name: GWM_UI
        component_params:
          SKIP_PREFLIGHT_CHECK: true
          GWM_API_VERSION: v1
          DEFAULT_GWM_INTERFACE_HOST: gbc
          DEFAULT_GWM_INTERFACE_PORT: 8080
          DEFAULT_GWM_INTERFACE_PROTOCOL: ws
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
- name: Gazebo and AMR deployments
  hosts: localhost
  strategy: free
  connection: local
  tasks:
    - name: Gazebo Deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: gazebo
        component_name: gazebo
        component_alias: gazebo
        present: false
        package_name: rio_gazebo
        networks:
          static_routes:
            - name: gazebo-ui
              endpoint_name: VNC_EP
          native_networks:
            - name: native_network
        component_params:
          VNC_PASSWORD: rapyuta
          VNC_RESOLUTION: 1920x1080
          DEBUG: true
          RACK: true
          WORLD: tatsumi
          ITEM_SPAWN_FROM: AUTO
          GWM_AUTH_TOKEN: autobootstrap

    - name: AMR1 Deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: amr1
        component_name: amr
        component_alias: amr1
        present: false
        package_name: rio_amr_pa
        networks:
          native_networks:
            - name: native_network
        component_params:
          ROBOT_MODEL: rr_pa_amr
          ROBOT_NAV_MODEL: rr_pa_amr
          NAV_STRATEGY: graph_guided
          MAP: tatsumi
          MAP_ID: 1
          WORLD2MAP_X: 0
          WORLD2MAP_Y: 0
          WORLD2MAP_Z: 0
          WORLD2MAP_YAW: 0
          IDLE_TIMEOUT: 1000000
          AGENT_ID: 1
          X_POS: 6.2
          Y_POS: 12
          Z_POS: 0.0
          YAW: 1.57

    - name: AMR2 Deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: amr2
        component_name: amr
        component_alias: amr2
        present: false
        package_name: rio_amr_pa
        networks:
          native_networks:
            - name: native_network
        component_params:
          ROBOT_MODEL: rr_pa_amr
          ROBOT_NAV_MODEL: rr_pa_amr
          NAV_STRATEGY: graph_guided
          MAP: tatsumi
          MAP_ID: 1
          WORLD2MAP_X: 0
          WORLD2MAP_Y: 0
          WORLD2MAP_Z: 0
          WORLD2MAP_YAW: 0
          IDLE_TIMEOUT: 1000000
          AGENT_ID: 2
          X_POS: 11
          Y_POS: 12
          Z_POS: 0.0
          YAW: 1.57

    - name: AMR3 Deployment
      async: 2000
      poll: 0
      rapyuta.rr_io.deployments:
        name: amr3
        component_name: amr
        component_alias: amr3
        present: false
        package_name: rio_amr_pa
        networks:
          native_networks:
            - name: native_network
        component_params:
          ROBOT_MODEL: rr_pa_amr
          ROBOT_NAV_MODEL: rr_pa_amr
          NAV_STRATEGY: graph_guided
          MAP: tatsumi
          MAP_ID: 1
          WORLD2MAP_X: 0
          WORLD2MAP_Y: 0
          WORLD2MAP_Z: 0
          WORLD2MAP_YAW: 0
          IDLE_TIMEOUT: 1000000
          AGENT_ID: 3
          X_POS: 13.6
          Y_POS: 1.3
          Z_POS: 0.0
          YAW: 1.57
      register: amr3_id
    
    # - name: "AMR3 - check on async status"
    #   async_status:
    #     jid: "{{ amr3_id.ansible_job_id}}"
    #   register: amr3_log
    #   until: amr3_log.finished
    #   retries: 30

    - name: dump test output
      debug:
        msg: '{{ amr3_id }}'

