name: daily_package_updater

on:
  # Run early morning Mon-Fri JST (cron job times in UTC)
  schedule:
    - cron:  '0 21 * * 0,1,2,3,4'
  # For manual triggers
  workflow_dispatch:

jobs:
  update_packages:
    name: "Update amr deployment packages"
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
       curl https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
       sudo python3 get-pip.py
       sudo python3 -m pip install ansible rapyuta-io

    - name: delete branch if exists
      continue-on-error: true
      run: git push origin --delete prbot/package_update_$(date +%F)

    - name: Create branch
      run: |
        hub checkout -b prbot/package_update_$(date +%F)
        hub pull origin rr_devel
      
    - name: remove get-pip file
      continue-on-error: true
      run: rm get-pip.py   
      
    - name: Run playbook update script
      run: |
        python scripts/manifest_updater.py -p ${{ secrets.IO_AMR_PROJECT }} -a ${{ secrets.IO_AUTH_TOKEN }}
        python scripts/update_deploy_configs.py

    - name: create branch
      run: git push origin prbot/package_update_$(date +%F)
      
    - name: Check Git Diff
      id: diff
      run: git diff --name-only origin/rr_devel prbot/package_update_$(date +%F)
      
    - name: Create PR
      if: contains(steps.diff.outputs, 'package')
      run: |
        hub config user.email "larry.ng@rapyuta-robotics.com" && hub config user.name "Larry Ng" && git status --porcelain | awk '{ print $2}' | xargs -n1 -I repo_name sh -c '{ git add repo_name; git commit --author "$(cd repo_name; git log -1 --pretty="%an <%ae>"; cd ..)" -m "`cd repo_name; git log -1 --pretty="%s"; cd ..`"; echo repo_name; }'
        hub pull-request -m "Package Update on $(date +%F)" -p -f -b rr_devel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
